/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portalform;

import java.awt.Color;
import com.form.*;
import java.util.ArrayList;
/**
 *
 * @author mohammed
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */

    private PersonData personalData;
    private ArrayList<EducationSection> educationSectionList=new ArrayList<>();
    private ArrayList<AddressSection> addressSectionList=new ArrayList<>();
    private ArrayList<AreasOfSpecializationSection> areaList=new ArrayList<>();

    private DentistBuilder dentistBuilder;

    
    
    public MainForm() {
        initComponents();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        basisPanel = new javax.swing.JPanel();
        personalInformationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        website = new javax.swing.JTextField();
        informationContinuePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        biographyPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        licenseCountry = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        licenseNumber = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        yearsInPractice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        biographyContinuePanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        educationPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        degree = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        major = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        School = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        educationContinuePanel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        educationAddMorePanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        addressPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        postalCode = new javax.swing.JTextField();
        addressContinuePanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        addressAddmorePanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        specialtyPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        specialistCountry = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        specialistState = new javax.swing.JTextField();
        SpecialistCheckBox = new javax.swing.JCheckBox();
        specialtyAddMorePanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        savePanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        selectionPanel = new javax.swing.JPanel();
        previewPanel = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        widgetPanel = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(22, 21, 227));

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        basisPanel.setBackground(new java.awt.Color(254, 254, 254));
        basisPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Chandas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 101, 101));
        jLabel1.setText("New Dentist");

        firstName.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        firstName.setForeground(new java.awt.Color(51, 51, 51));
        firstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel2.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 101, 101));
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 101, 101));
        jLabel3.setText("Last Name");

        lastName.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        lastName.setForeground(new java.awt.Color(51, 51, 51));
        lastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel4.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(101, 101, 101));
        jLabel4.setText("Email Address");

        emailAddress.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        emailAddress.setForeground(new java.awt.Color(51, 51, 51));
        emailAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel5.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(101, 101, 101));
        jLabel5.setText("Phone Number");

        phoneNumber.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(51, 51, 51));
        phoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel6.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(101, 101, 101));
        jLabel6.setText("Website");

        website.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        website.setForeground(new java.awt.Color(51, 51, 51));
        website.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        informationContinuePanel.setBackground(new java.awt.Color(22, 21, 227));
        informationContinuePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informationContinuePanelMouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("continue (1/5)");

        javax.swing.GroupLayout informationContinuePanelLayout = new javax.swing.GroupLayout(informationContinuePanel);
        informationContinuePanel.setLayout(informationContinuePanelLayout);
        informationContinuePanelLayout.setHorizontalGroup(
            informationContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
        informationContinuePanelLayout.setVerticalGroup(
            informationContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout personalInformationPanelLayout = new javax.swing.GroupLayout(personalInformationPanel);
        personalInformationPanel.setLayout(personalInformationPanelLayout);
        personalInformationPanelLayout.setHorizontalGroup(
            personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInformationPanelLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(website, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalInformationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informationContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        personalInformationPanelLayout.setVerticalGroup(
            personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInformationPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informationContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        basisPanel.add(personalInformationPanel, "card2");

        jLabel7.setFont(new java.awt.Font("Chandas", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(101, 101, 101));
        jLabel7.setText("Biography Section");

        jLabel8.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(101, 101, 101));
        jLabel8.setText("License Country");

        licenseCountry.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        licenseCountry.setForeground(new java.awt.Color(51, 51, 51));
        licenseCountry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel9.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(101, 101, 101));
        jLabel9.setText("License Number");

        licenseNumber.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        licenseNumber.setForeground(new java.awt.Color(51, 51, 51));
        licenseNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        gender.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(51, 51, 51));
        gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel11.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(101, 101, 101));
        jLabel11.setText("Gender");

        yearsInPractice.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        yearsInPractice.setForeground(new java.awt.Color(51, 51, 51));
        yearsInPractice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel12.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(101, 101, 101));
        jLabel12.setText("Years in Practice");

        biographyContinuePanel.setBackground(new java.awt.Color(22, 21, 227));
        biographyContinuePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biographyContinuePanelMouseClicked(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("continue (2/5)");

        javax.swing.GroupLayout biographyContinuePanelLayout = new javax.swing.GroupLayout(biographyContinuePanel);
        biographyContinuePanel.setLayout(biographyContinuePanelLayout);
        biographyContinuePanelLayout.setHorizontalGroup(
            biographyContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        biographyContinuePanelLayout.setVerticalGroup(
            biographyContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout biographyPanelLayout = new javax.swing.GroupLayout(biographyPanel);
        biographyPanel.setLayout(biographyPanelLayout);
        biographyPanelLayout.setHorizontalGroup(
            biographyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biographyPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel7)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(biographyPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(biographyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biographyPanelLayout.createSequentialGroup()
                        .addGroup(biographyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(licenseCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 298, Short.MAX_VALUE))
                    .addGroup(biographyPanelLayout.createSequentialGroup()
                        .addGroup(biographyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(yearsInPractice, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(biographyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biographyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(biographyContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        biographyPanelLayout.setVerticalGroup(
            biographyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biographyPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(biographyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(biographyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(licenseCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(licenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearsInPractice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(biographyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biographyContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        basisPanel.add(biographyPanel, "card3");

        jLabel13.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(101, 101, 101));
        jLabel13.setText("Degree");

        degree.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        degree.setForeground(new java.awt.Color(51, 51, 51));
        degree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel14.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(101, 101, 101));
        jLabel14.setText("Major");

        major.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        major.setForeground(new java.awt.Color(51, 51, 51));
        major.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel15.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(101, 101, 101));
        jLabel15.setText("School");

        School.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        School.setForeground(new java.awt.Color(51, 51, 51));
        School.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel16.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(101, 101, 101));
        jLabel16.setText("Year");

        year.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        year.setForeground(new java.awt.Color(51, 51, 51));
        year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel17.setFont(new java.awt.Font("Chandas", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(101, 101, 101));
        jLabel17.setText("Education Section");

        educationContinuePanel.setBackground(new java.awt.Color(22, 21, 227));
        educationContinuePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                educationContinuePanelMouseClicked(evt);
            }
        });

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("continue (3/5)");

        javax.swing.GroupLayout educationContinuePanelLayout = new javax.swing.GroupLayout(educationContinuePanel);
        educationContinuePanel.setLayout(educationContinuePanelLayout);
        educationContinuePanelLayout.setHorizontalGroup(
            educationContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        educationContinuePanelLayout.setVerticalGroup(
            educationContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        educationAddMorePanel.setBackground(new java.awt.Color(22, 21, 227));
        educationAddMorePanel.setPreferredSize(new java.awt.Dimension(128, 42));
        educationAddMorePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                educationAddMorePanelMouseClicked(evt);
            }
        });

        jLabel30.setForeground(new java.awt.Color(242, 241, 240));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("add more");

        javax.swing.GroupLayout educationAddMorePanelLayout = new javax.swing.GroupLayout(educationAddMorePanel);
        educationAddMorePanel.setLayout(educationAddMorePanelLayout);
        educationAddMorePanelLayout.setHorizontalGroup(
            educationAddMorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        educationAddMorePanelLayout.setVerticalGroup(
            educationAddMorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel17)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(School, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(218, 336, Short.MAX_VALUE))
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(educationAddMorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(educationContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addGap(28, 28, 28)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(School, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(educationContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(educationAddMorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        basisPanel.add(educationPanel, "card4");

        jLabel18.setFont(new java.awt.Font("Chandas", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(101, 101, 101));
        jLabel18.setText("Address Section");

        jLabel19.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(101, 101, 101));
        jLabel19.setText("Country");

        country.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        country.setForeground(new java.awt.Color(51, 51, 51));
        country.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel20.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(101, 101, 101));
        jLabel20.setText("State");

        state.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        state.setForeground(new java.awt.Color(51, 51, 51));
        state.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel21.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(101, 101, 101));
        jLabel21.setText("City");

        city.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        city.setForeground(new java.awt.Color(51, 51, 51));
        city.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        street.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        street.setForeground(new java.awt.Color(51, 51, 51));
        street.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        jLabel22.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(101, 101, 101));
        jLabel22.setText("Street");

        jLabel23.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(101, 101, 101));
        jLabel23.setText("Postal Code");

        postalCode.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        postalCode.setForeground(new java.awt.Color(51, 51, 51));
        postalCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));

        addressContinuePanel.setBackground(new java.awt.Color(22, 21, 227));
        addressContinuePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressContinuePanelMouseClicked(evt);
            }
        });

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("continue (4/5)");

        javax.swing.GroupLayout addressContinuePanelLayout = new javax.swing.GroupLayout(addressContinuePanel);
        addressContinuePanel.setLayout(addressContinuePanelLayout);
        addressContinuePanelLayout.setHorizontalGroup(
            addressContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        addressContinuePanelLayout.setVerticalGroup(
            addressContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        addressAddmorePanel.setBackground(new java.awt.Color(22, 21, 227));
        addressAddmorePanel.setPreferredSize(new java.awt.Dimension(128, 42));
        addressAddmorePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressAddmorePanelMouseClicked(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(242, 241, 240));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("add more");

        javax.swing.GroupLayout addressAddmorePanelLayout = new javax.swing.GroupLayout(addressAddmorePanel);
        addressAddmorePanel.setLayout(addressAddmorePanelLayout);
        addressAddmorePanelLayout.setHorizontalGroup(
            addressAddmorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        addressAddmorePanelLayout.setVerticalGroup(
            addressAddmorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel18)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addressPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addressAddmorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addressContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel18)
                .addGap(28, 28, 28)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addressPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addressContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressAddmorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        basisPanel.add(addressPanel, "card5");

        specialtyPanel.setBackground(new java.awt.Color(254, 254, 254));

        jLabel24.setFont(new java.awt.Font("Chandas", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(101, 101, 101));
        jLabel24.setText("specialty");

        jLabel25.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(101, 101, 101));
        jLabel25.setText("Area of specialization");

        specialistCountry.setEditable(false);
        specialistCountry.setBackground(new java.awt.Color(169, 162, 153));
        specialistCountry.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        specialistCountry.setForeground(new java.awt.Color(51, 51, 51));
        specialistCountry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));
        specialistCountry.setDoubleBuffered(true);
        specialistCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialistCountryActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Chilanka", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(101, 101, 101));
        jLabel26.setText("start Year");

        specialistState.setEditable(false);
        specialistState.setBackground(new java.awt.Color(169, 162, 153));
        specialistState.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        specialistState.setForeground(new java.awt.Color(51, 51, 51));
        specialistState.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(101, 101, 101)));
        specialistState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialistStateActionPerformed(evt);
            }
        });

        SpecialistCheckBox.setText("is Specialist");
        SpecialistCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpecialistCheckBoxMouseClicked(evt);
            }
        });
        SpecialistCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialistCheckBoxActionPerformed(evt);
            }
        });

        specialtyAddMorePanel.setBackground(new java.awt.Color(22, 21, 227));
        specialtyAddMorePanel.setPreferredSize(new java.awt.Dimension(128, 42));
        specialtyAddMorePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                specialtyAddMorePanelMouseClicked(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(242, 241, 240));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("add more");

        javax.swing.GroupLayout specialtyAddMorePanelLayout = new javax.swing.GroupLayout(specialtyAddMorePanel);
        specialtyAddMorePanel.setLayout(specialtyAddMorePanelLayout);
        specialtyAddMorePanelLayout.setHorizontalGroup(
            specialtyAddMorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        specialtyAddMorePanelLayout.setVerticalGroup(
            specialtyAddMorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        savePanel.setBackground(new java.awt.Color(22, 21, 227));
        savePanel.setPreferredSize(new java.awt.Dimension(128, 42));
        savePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePanelMouseClicked(evt);
            }
        });

        jLabel33.setForeground(new java.awt.Color(242, 241, 240));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("save");

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout specialtyPanelLayout = new javax.swing.GroupLayout(specialtyPanel);
        specialtyPanel.setLayout(specialtyPanelLayout);
        specialtyPanelLayout.setHorizontalGroup(
            specialtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialtyPanelLayout.createSequentialGroup()
                .addGroup(specialtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(specialtyPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(specialtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(specialistCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpecialistCheckBox)
                            .addComponent(jLabel26)
                            .addComponent(specialistState, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialtyPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(specialtyAddMorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(specialtyPanelLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel24)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        specialtyPanelLayout.setVerticalGroup(
            specialtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialtyPanelLayout.createSequentialGroup()
                .addGroup(specialtyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(specialtyPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(specialtyPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel24)
                        .addGap(9, 9, 9)
                        .addComponent(SpecialistCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(specialistCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(specialistState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(specialtyAddMorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        basisPanel.add(specialtyPanel, "card6");

        selectionPanel.setBackground(new java.awt.Color(254, 254, 254));

        previewPanel.setBackground(new java.awt.Color(236, 235, 234));
        previewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewPanelMouseClicked(evt);
            }
        });

        jPanel18.setBackground(new java.awt.Color(22, 21, 227));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portalform/user (6).png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        jLabel36.setFont(new java.awt.Font("Chilanka", 1, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(101, 101, 101));
        jLabel36.setText("Preview Form");

        jLabel38.setFont(new java.awt.Font("Chilanka", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(101, 101, 101));
        jLabel38.setText("show all details");

        javax.swing.GroupLayout previewPanelLayout = new javax.swing.GroupLayout(previewPanel);
        previewPanel.setLayout(previewPanelLayout);
        previewPanelLayout.setHorizontalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewPanelLayout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel38))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        previewPanelLayout.setVerticalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(previewPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(previewPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGap(18, 18, 18))
        );

        widgetPanel.setBackground(new java.awt.Color(236, 235, 234));
        widgetPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                widgetPanelMouseClicked(evt);
            }
        });

        jPanel20.setBackground(new java.awt.Color(22, 21, 227));

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portalform/user (6).png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        jLabel37.setFont(new java.awt.Font("Chilanka", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(101, 101, 101));
        jLabel37.setText("Widget Preview Form");

        jLabel39.setFont(new java.awt.Font("Chilanka", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(101, 101, 101));
        jLabel39.setText("Show as digital card ");

        javax.swing.GroupLayout widgetPanelLayout = new javax.swing.GroupLayout(widgetPanel);
        widgetPanel.setLayout(widgetPanelLayout);
        widgetPanelLayout.setHorizontalGroup(
            widgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(widgetPanelLayout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(widgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel39))
                .addGap(0, 82, Short.MAX_VALUE))
        );
        widgetPanelLayout.setVerticalGroup(
            widgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, widgetPanelLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(widgetPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout selectionPanelLayout = new javax.swing.GroupLayout(selectionPanel);
        selectionPanel.setLayout(selectionPanelLayout);
        selectionPanelLayout.setHorizontalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(widgetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        selectionPanelLayout.setVerticalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(previewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(widgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        basisPanel.add(selectionPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(basisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void informationContinuePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationContinuePanelMouseClicked
        // TODO add your handling code here:
        personalInformationPanel.hide();
        biographyPanel.show();
        
        String _firstName=firstName.getText();
        String _lastName=lastName.getText();
        String _emailAddress=emailAddress.getText();
        String _website=website.getText();
        String _phoneNumber=phoneNumber.getText();
        

        personalData = new PersonData(_firstName,_lastName,_emailAddress,_website,_phoneNumber);
        
    }//GEN-LAST:event_informationContinuePanelMouseClicked

    private void biographyContinuePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biographyContinuePanelMouseClicked
        // TODO add your handling code here:
        biographyPanel.hide();
        educationPanel.show();
        
          String _licenseCountryName=licenseCountry.getText();
          String _licenseNumber=licenseNumber.getText();
          int _yearInPractice=Integer.parseInt(yearsInPractice.getText());
          String _gender=gender.getText();

          personalData.setLicenseCountryName(_licenseCountryName);
          personalData.setLicenseNumber(_licenseNumber);
          personalData.setYearInPractice(_yearInPractice);
          personalData.setGender(_gender);
          
    }//GEN-LAST:event_biographyContinuePanelMouseClicked

    private void educationContinuePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_educationContinuePanelMouseClicked
        // TODO add your handling code here:
        educationPanel.hide();
        addressPanel.show();
        if(!degree.getText().isEmpty() || !degree.getText().isBlank()){
            
            String _degree=degree.getText();
            String _major=major.getText();
            String _school=School.getText();
            String _year=year.getText();
            educationSectionList.add(new EducationSection(_degree, _major, _school, _year));
        }
    }//GEN-LAST:event_educationContinuePanelMouseClicked

    private void addressContinuePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressContinuePanelMouseClicked
        // TODO add your handling code here:
        addressPanel.hide();
        specialtyPanel.show();
        if(!country.getText().isEmpty() || !country.getText().isBlank()){
            
            String _country=country.getText();
            String _state=state.getText();
            String _city=city.getText();
            String _street=street.getText();
            int _postalCode=Integer.parseInt(postalCode.getText());
            addressSectionList.add(new AddressSection(_country, _state, _city, _street, _postalCode));
            
        }
    }//GEN-LAST:event_addressContinuePanelMouseClicked

    private void SpecialistCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialistCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialistCheckBoxActionPerformed

    private void specialistCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialistCountryActionPerformed
        // TODO add your handling code here:
        specialistCountry.setBackground(new Color(169,162,153));
       
    }//GEN-LAST:event_specialistCountryActionPerformed

    private void SpecialistCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialistCheckBoxMouseClicked
        // TODO add your handling code here:
        if(SpecialistCheckBox.isSelected()){
            specialistCountry.setEditable(true);
            specialistState.setEditable(true);
            specialistState.setBackground(new Color(242,241,240));
            specialistCountry.setBackground(new Color(242,241,240));
            
        }
        else
        {
            specialistCountry.setEditable(false);
            specialistState.setEditable(false);
            specialistState.setBackground(new Color(169,162,153));
            specialistCountry.setBackground(new Color(169,162,153));
            
        }
    }//GEN-LAST:event_SpecialistCheckBoxMouseClicked

    private void specialistStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialistStateActionPerformed
        // TODO add your handling code here:
        specialistState.setBackground(new Color(169,162,153));
    }//GEN-LAST:event_specialistStateActionPerformed

    private void educationAddMorePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_educationAddMorePanelMouseClicked
        // TODO add your handling code here:
        
     String _degree=degree.getText();
     String _major=major.getText();
     String _school=School.getText();
     String _year=year.getText();
     educationSectionList.add(new EducationSection(_degree, _major, _school, _year));
     
     degree.setText("");
     major.setText("");
     School.setText("");
     year.setText("");
     
    }//GEN-LAST:event_educationAddMorePanelMouseClicked

    private void addressAddmorePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressAddmorePanelMouseClicked
        // TODO add your handling code here:
        
     String _country=country.getText();
     String _state=state.getText();
     String _city=city.getText();
     String _street=street.getText();
     int _postalCode=Integer.parseInt(postalCode.getText());
     addressSectionList.add(new AddressSection(_country, _state, _city, _street, _postalCode));
     
     country.setText("");
     state.setText("");
     city.setText("");
     street.setText("");
     postalCode.setText("");
     
    }//GEN-LAST:event_addressAddmorePanelMouseClicked

    private void specialtyAddMorePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialtyAddMorePanelMouseClicked
        // TODO add your handling code here:
        if(SpecialistCheckBox.isSelected()){
             String areasOfSpecialization=specialistCountry.getText();
             int startYear=Integer.parseInt(specialistState.getText());
             areaList.add(new AreasOfSpecializationSection(areasOfSpecialization, startYear));
        }
    }//GEN-LAST:event_specialtyAddMorePanelMouseClicked

    private void savePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePanelMouseClicked

        specialtyPanel.hide();
        selectionPanel.show();
        if(SpecialistCheckBox.isSelected()&&(!country.getText().isEmpty() || !country.getText().isBlank())){
            String areasOfSpecialization=specialistCountry.getText();
             int startYear=Integer.parseInt(specialistState.getText());
             areaList.add(new AreasOfSpecializationSection(areasOfSpecialization, startYear));
            dentistBuilder= new DentistBuilder.DentistFinderBuilder().personalData(personalData).educationSectionList(educationSectionList)
                            .addressSectionList(addressSectionList).areaList(areaList).build();
        }
        else
            dentistBuilder= new DentistBuilder.DentistFinderBuilder().personalData(personalData).educationSectionList(educationSectionList)
                    .addressSectionList(addressSectionList).build();
        
        
    }//GEN-LAST:event_savePanelMouseClicked

    private void previewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewPanelMouseClicked
        // TODO add your handling code here:
        PreviewForm previewForm =new PreviewForm();
        previewForm.setDentistFinder(dentistBuilder);
        
        previewForm.setVisible(true);
    }//GEN-LAST:event_previewPanelMouseClicked

    private void widgetPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_widgetPanelMouseClicked
        // TODO add your handling code here:
        WidgetPreviewForm widgetForm =new WidgetPreviewForm(personalData, addressSectionList);
        widgetForm.setVisible(true);
    }//GEN-LAST:event_widgetPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField School;
    private javax.swing.JCheckBox SpecialistCheckBox;
    private javax.swing.JPanel addressAddmorePanel;
    private javax.swing.JPanel addressContinuePanel;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JPanel basisPanel;
    private javax.swing.JPanel biographyContinuePanel;
    private javax.swing.JPanel biographyPanel;
    private javax.swing.JTextField city;
    private javax.swing.JTextField country;
    private javax.swing.JTextField degree;
    private javax.swing.JPanel educationAddMorePanel;
    private javax.swing.JPanel educationContinuePanel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField gender;
    private javax.swing.JPanel informationContinuePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField licenseCountry;
    private javax.swing.JTextField licenseNumber;
    private javax.swing.JTextField major;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel personalInformationPanel;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField postalCode;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JPanel savePanel;
    private javax.swing.JPanel selectionPanel;
    private javax.swing.JTextField specialistCountry;
    private javax.swing.JTextField specialistState;
    private javax.swing.JPanel specialtyAddMorePanel;
    private javax.swing.JPanel specialtyPanel;
    private javax.swing.JTextField state;
    private javax.swing.JTextField street;
    private javax.swing.JTextField website;
    private javax.swing.JPanel widgetPanel;
    private javax.swing.JTextField year;
    private javax.swing.JTextField yearsInPractice;
    // End of variables declaration//GEN-END:variables
}
